apiVersion: v1
kind: Service
metadata:
  name: kuber-service-headless
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
